### ISSUE TITLE
investigate signing commits or release tags with gpg key

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/rfcs#16]
I've been thinking about this lately, I've seen other mozillia people signing their commits.  I'm not sure that every commit needs to be signed, however I do think that at least signing release tags would be a good thing going forward. 

https://help.github.com/articles/signing-commits-using-gpg/

**Comment by jryans** [comment]
We could do it, but I am not sure it really has that much value for DevTools? Since we are in control of what ships to end users, I am not sure what's gained (other than a neat check mark in the commit log). If you see other benefits, I'd like to hear about it!

**Comment by clarkbw** [comment]
I see, good point.  I was thinking mostly about the `devtools-core` type repos and how a release is tagged there.

**Comment by jryans** [comment]
Ah, I see. At the moment, we don't seem to push tags for `devtools-core` at all, so maybe we should think through that step first. I guess it's a bit awkward with multiple independently versioned packages and a single namespace for tags, so the tag might need to be `<package>-<version>`.

Maybe we should script this releasing step, so that it happens consistently for all packages no matter who does them. Then, it would be (relatively) easy to add something like signing (if we wish to do so) by updating that script.

**Comment by juliandescottes** [comment]
This is part of a bigger conversation on the release process for DevTools packages published on GitHub.
