### ISSUE TITLE
Naming convention for react component files

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/rfcs#17]
There seem to be no rule for naming react component files.

Some options:

1) Using (lowercase -hyphened name): file-name.js
This seems to be used for the current m-c style but, there are exceptions

2) Using CameCase.js
Standard in React community

We might want to use the same style for all files (not only for React components)

Honza

**Comment by jasonLaster** [comment]
@janodvarko We've used CamelCasing in our components. Our utils on the other hand are hyphenated though.

**Comment by juliandescottes** [comment]
I guess the most sensible options here are either:
- leave as is
- update React components in m-c to use lowercase+hyphen
- update React components in m-c to use CamelCase

The React components in the inspector seem to be using CamelCase.
All the other components I could find in mozilla-central seem to be using lowercase+hyphen.

Following a common naming convention makes sense here. Since React's naming convention clearly states that components should use PascalCase I would be in favour of following that. 

Can we get feedback from other peers dealing with React components in m-c? @nchevobbe @gl @gregtatum

**Comment by janodvarko** [comment]
I am also voting for using CamelCase (since it's the standard in React community)
Honza

**Comment by nchevobbe** [comment]
I'm okay for PascalCasing components in m-c (as well as in devtools-core I guess).

**Comment by nyrosmith** [comment]
I suggest to use the same as the community -> CamelCase

**Comment by gabrielluong** [comment]
We already use CamelCase in the Inspector to follow the standard.

**Comment by gregtatum** [comment]
CamelCase for the win.

**Comment by juliandescottes** [comment]
This RFC was just accepted: all React components should use CamelCase (or PascalCase to be really accurate).

Before closing the issue, we should follow-up by creating a meta bug in Bugzilla to convert our React components to the new convention. @janodvarko are you OK to take care of that?

> We might want to use the same style for all files (not only for React components)

Regarding the last part of the initial proposal (ie use the same style for all files, not just React components), this was not really discussed here and if someone feels strongly about it, it should go to a separate RFC.

**Comment by janodvarko** [comment]
> CamelCase for the win.

Hooray!

> @janodvarko are you OK to take care of that?

Meta bug reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1402359
I'll be filing follow-ups soon.

Honza

**Comment by juliandescottes** [comment]
Thanks Honza! Closing the issue :)

**Comment by captainbrosset** [comment]
For info the work is happening on https://bugzilla.mozilla.org/show_bug.cgi?id=1402359

**Comment by captainbrosset** [comment]
All children bugs of the meta are either resolved or about to be! 
Congrats on our first RFC being discussed, agreed, and acted upon. This seemed like a good process to me.
