### ISSUE TITLE
Switch to native EventTarget when possible

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/rfcs#39]
As far as I understand, in Firefox 59 landed a patch that allowed to extend `EventTarget`:  https://bugzilla.mozilla.org/show_bug.cgi?id=1379688

I was wondering if we could use this as an opportunity to get rid of our custom `EventEmitter` [[1]](https://searchfox.org/mozilla-central/source/devtools/shared/old-event-emitter.js) [[2]](https://searchfox.org/mozilla-central/source/devtools/shared/event-emitter.js) utils.

We could have a simple class wrapper around `EventTarget` to implements the methods we're used to (emit, on, off, once, …)

```js
class EventEmitter extends EventTarget {
  on(eventName, cb, options) {
    return this.addEventListener(eventName, cb, options)
  }

  off(eventName, ref) {
    this.removeEventListener(eventName, ref);
  }

  once(eventName) {
    return new Promise(res => this.addEventListener(eventName, res, {once: true}));
  }

  emit(eventName, options = {}) {
    this.dispatchEvent(new CustomEvent(eventName, options));
  }
}
```

I don't expect it to have a huge impact on performances, but at least we're relying on a platform API, which means that we'd benefit from any improvements made there, and I suspect this would save some memory usage (not sure) ?

We don't have to do it in one big chunk of work but could make small actionable bugs to switch from an "old" eventEmitter to EventTarget.

What do you think ? Is there anything we could miss by using EventTarget ?

**Comment by ochameau** [comment]
> I was wondering if we could use this as an opportunity to get rid of our custom EventEmitter [1] [2] utils.
> We could have a simple class wrapper around EventTarget to implements the methods we're used to (emit, on, off, once, …)

This is contradictory. We wouldn't switch to EventTarget if we use an EventEmitter wrapper everywhere.
I wouldn't suggest switching to pure EventTarget API everywhere as this API is just more verbose and less usable than EventEmitter.

> I don't expect it to have a huge impact on performances, but at least we're relying on a platform API, which means that we'd benefit from any improvements made there, and I suspect this would save some memory usage (not sure) ?

I would expect a negative impact on perf rather than a positive one. This API is most likely not implemented in JS (some are, this is the one you see with "self-hosted" in your stacks). It means two things that are bad regarding perf:
* it forces to cross languages JS <-> C++. There is some slight overhead when you have to call C++ from JS. The opposite is most likely true as well.
* it breaks the JIT. Anytime you call a C++ function, the JIT is disabled. While when you have a JS only codebase, it still can work. This is why we try to implement some platform features in JS. (the self hosted)
I'm curious about why you think it is possibly improving memory and computations?

I would rather encourage to finish the event emitter refactoring rather than piling up any new refactoring.
We still use the old-event-emitter module in 116 places:
https://searchfox.org/mozilla-central/search?q=old-event-emitter&case=true&regexp=false&path=
And also still use deprecated functions from the new one, like doing:
  EventEmitter.on(target, "event", listener)
Instead of:
  target.on("event", listener);

**Comment by juliandescottes** [comment]
> I'm curious about why you think it is possibly improving memory and computations?

Can't answer for Nicolas but I would naively assume the same :) So I'll just share why

When using a platform API written in C++, I would expect it to perform better than a JS implementation, because JS is still known to be slower than C++. Same for memory management, JS uses garbage collection so in theory it should consume more memory than a good implementation in C++ with explicit memory management.

Now with your two explanations I understand how that might not be the case, but I don't think it's that weird to assume the opposite if you don't know that.

> I would rather encourage to finish the event emitter refactoring rather than piling up any new refactoring.

Completely agree with that, if we were to accept this, I would still prefer to block it on the migration of old-event-emitter to event-emitter, and avoid having three implementations competing with each other.

**Comment by nchevobbe** [comment]
> I'm curious about why you think it is possibly improving memory and computations?

Same answer as Julian :) 

Agreed with finishing the current work on EventEmitter

**Comment by jryans** [comment]
Assuming people think the API proposed here is reasonable (not sure if that's been discussed in detail yet), then I think this is something we first need to gather data about before proceeding.

Someone could try it out, measure the performance and memory differences vs. current code, and then we can proceed towards a decision based on that. It can be tricky to predict the impact sometimes, so always better to measure if it's not so hard to do.

(I also agree finishing existing refactorings seems like a worthwhile first step.)

**Comment by sole** [comment]
This is the top level bug for eventemitter migration https://bugzilla.mozilla.org/showdependencytree.cgi?id=1402840&hide_resolved=1

**Comment by ochameau** [comment]
Too bad Eddy isn't around anymore, he would have debunked the "idolatry"[1] of C++ over JS :)
[1] I'm exaggerating here.

I wish there was docs about JIT breaking with C++ calls, same for the overhead of C++ calls from JS, the cost of wrappers, compartments and all the dark magic of a browser.
I think it is important for our team to be aware of that. I imagine I was surprised that this knowledge wasn't spread (it used to, I believe).

> Assuming people think the API proposed here is reasonable (not sure if that's been discussed in detail yet), then I think this is something we first need to gather data about before proceeding.

I'm not sure there is any API to be changed if I follow correctly. It would be only a change within event-emitter.js implementation? At the end it sounds like the original proposal would better fit in bugzilla, with what you said. A patch, a talos run and act from here. Doing that or not won't have much impact on devtools code.

**Comment by julienw** [comment]
I don't see where we're going with this proposal. Are there any perf issue with our existing EventEmitter?

I agree with @ochameau: finishing the migration is top priority around event emitter, then it's easy to change the implementation of that EventEmitter class if we need it.

**Comment by bgrins** [comment]
If I'm reading the proposal correctly, this is tangential to the EventEmitter migration. It looks like the request here is not to change the API of the event emitter, but to swap out its implementation with something else.

If that's the case, we could run existing tests and measure performance pretty easily. If performance was unchanged I'd prefer to use the proposed version than our current implementation because:

1) It's less code
2) We could expose better tooling for it (which would also benefit web developers). For example, we have a [bug on file](https://bugzilla.mozilla.org/show_bug.cgi?id=1419089 ) to show the event bubble for EventTargets in the console / debugger UI.

**Comment by juliandescottes** [comment]
Echoing several comments above, it seems reasonable to move this to a bug where we try to swap the implementation of event-emitter (and maybe old-event-emitter) to rely on EventTarget, and gather data about the performance. 

@nchevobbe can you create the bug?

Refactoring and migrating code to directly use EventTarget is 1/ blocked on the old-event-emitter migration, 2/ blocked on assessing the performance via the exercise mentioned above. So it's probably a bit early to consider it.

**Comment by nchevobbe** [comment]
I created [Bug 1441111](https://bugzilla.mozilla.org/show_bug.cgi?id=1441111) to experiment on this.
I also agree that we should finish the current EventEmitter work (did it for the console).

I shouldn't have brought this only for a performance point of view. Here we have a native mechanism that we can use instead of rolling our own implementation, I think it's a nice opportunity to clean the code.

What it would bring us is consistency and familiarity when using those events, since we are used to DOM events. Our EventEmitter is slightly different from EventTarget (you can emit multiple arguments for example whereas all the data is in the first argument in DOM events), and it's something you have to remember / lookup when using them. This won't be fixed if we just keep using EventEmitter's abstractions, but something I had in mind.

Also, having those exposed in the debugger and console would be nice (we could have a way to see all listeners, with links to the debugger, a UI to fire a given event, …) and that would enable us dogfood our tooling around EventTarget if we rely on them.

**Comment by juliandescottes** [comment]
Closing this while we try EventTarget at the bug mentioned above, and while we finish the event emitter migration.
