### ISSUE TITLE
Standardize DevTools Panel initialization

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/rfcs#48]
The goal of this RFC is to standardize and simplify the initialization code for our panels. Should make it easier for peers to jump from one panel to the other. Also would love to address [Bug 1455421](https://bugzilla.mozilla.org/show_bug.cgi?id=1455421) as a side effect.

# Current status 

The initialization of most panels is split between three files: an index (html, xul etc...), a panel file, and a UI initializer file. There are small inconsistencies between panels both about naming and about the way files are loaded.

## Definitions.js build methods

All tools have the same build method in definitions.js:
```
  build: function(iframeWindow, toolbox) {
    return new InspectorPanel(iframeWindow, toolbox);
  }
```

## Panel file

The {Tool}Panel(win, toolbox) method is defined in a JS module required from definitions.js which is most often directly called panel.js, but sometimes {tool}-panel.js. This file should implement the "Panel" API which means implementing `open()` and `destroy()`.

## Index file

Some tools use a html file, some use a xul file and some use a xhtml file. Most of the time named `{toolname}.html|xhtml|xul`. This file is responsible for loading the CSS styles specific to the tool, the theme-switching.js file and most of the time an "initializer" file.

## Initializer file

The initializer is sometimes called initializer.js, main.js or sometimes called after the panel it represents (eg inspector.js, debugger.js). Its role is to initialize the UI. It is usually loaded via a script tag and has access to `window` etc...

## Breakdown by Panel

Expand the sections below if you want to see in details which files are used by our different panels.

<details>
  <summary>Details for maintained Panels</summary>

accessibility:
- index: accessibility.html
- scripts: main.js
- panel: accessibility-panel.js

application:
- index: index.html
- scripts: initializer.js
- panel: panel.js

debugger/new:
- index: index.html
- scripts: debugger.js, loaded via a BrowserLoader created in a script tag
- panel: panel.js

dom:
- index: dom.html
- scripts: main.js
- panel: dom-panel.js

inspector:
- index: inspector.xhtml
- scripts: inspector.js
- panel: panel.js

memory:
- index: memory.xhtml
- scripts: none (but loads some dependencies: d3.js, dagre-d3.js)
- panel: panel.js

netmonitor:
- index: index.html
- scripts: initializer.js
- panel: panel.js

performance-new:
- index: perf.xhtml
- scripts: initializer.js
- panel: panel.js

scratchpad:
- index: scratchpad.xul
- scripts: scratchpad.js
- panel: scratchpad-panel.js

storage:
- index: storage.xul
- scripts: none (there is a "ui.js", loaded from panel.js)
- panel: panel.js

styleeditor:
- index: styleeditor.xul
- scripts: none (there is a "StyleEditorUI.jsm", loaded from styleeditor-panel.js)
- panel: styleeditor-panel.js

webconsole:
- index: webconsole.html
- scripts: main.js
- panel: panel.js

</details>

<details>
  <summary>Details for Panels pending removal or rewrite</summary>

canvasdebugger:
- index: canvasdebugger.xul
- scripts: callslist.js, canvasdebugger.js, snapshotslist.js
- panel: panel.js

debugger:
- index: debugger.xul
- scripts: many scripts
- panel: panel.js

performance:
- index: performance.xul
- scripts: many scripts
- panel: panel.js

shadereditor:
- index: shadereditor.xul
- scripts: shadereditor.js
- panel: panel.js

webaudioeditor:
- index: webaudioeditor.xul
- scripts: many scripts, main file is probably controller.js
- panel: panel.js

</details>

# Proposal

This RFC is originally motivated by [Bug 1455421](https://bugzilla.mozilla.org/show_bug.cgi?id=1455421) which requires that we stop loading DevTools modules via `<script>` tags. This is typically how the initializer file is loaded.

This is the occasion to standardize and simplify the initialization of our panels. The panel and initializer files seem very similar, both according to their responsibilities and lifecycle, so maybe we can get rid of one, and stop loading anything via a `<script>` tag.

The proposal is to:
- merge "panel" and "initializer" to a single file
- decide on a consistent name for this file: "panel.js", "{toolname}-panel.js", "{toolname}.js"?
- load this file using the BrowserLoader from definitions.js
- decide on a consistent name for the index: "index.html", "{toolname}-index.html", "{toolname}.html" (or xul, or xhtml [1])

Interested to know if there is some added value that I missed with having separate files here. Are there concerns or limitations linked to using the BrowserLoader for everything UI related here?

[1] I believe some files use xhtml for no reason because they don't load any localization DTD. Inspector, memory and perf-new can probably use html now?

**Comment by ochameau** [comment]
> This RFC is originally motivated by Bug 1455421 which requires that we stop loading DevTools modules via <script> tags. This is typically how the initializer file is loaded.

I imagine I should elaborate here as I was the one suggesting doing that.
We have an issue regarding toolbox destruction.
When a toolbox is closed, we execute various cleanup code, including destruction functions within each opened tool. And sometime, we involve Promises and async functions coming from the panels.
But when a document is destroyed, its promises get frozen at some point and we can't avoid that.
This is a dark corner of DOM Promises which has been discussed in the spec [over here](https://github.com/w3ctag/promises-guide/issues/44).
It comes back to the rule that web pages are not guaranteed to execute anything on unload.

In order to mitigate that, we should:
- ideally, avoid doing much when destroying the toolbox and the tools,
- strictly avoid involving any Promise related to panels during toolbox destruction. These promises are:
  - the ones instanciated from its `window.Promise` constructor
  - `async` functions from scripts loaded via `<script>` tags

Then, getting rid of `<script>` tags is a good workaround to avoid any breakage of the toolbox while closing it.
But this is just a workaround. There is nothing really wrong in using script tags. Actually it feels more webby than using our custom module loader...

Having said that, I think the point your raised about each tool using an always different and unique setup is something we should address independently of this issue.


>- merge "panel" and "initializer" to a single file

Sounds good to me.

But I would like to raise another set of opportunities.
Today, we have JS calls from the toolbox to the panels in order to start them.
It would be great if tools were able to start themself independently of the toolbox.
This doesn't help:
- launchpad, as you have to workaround that to somehow call the same setup methods but with a mocked toolbox object. I think that was the main reason why we started having initializer modules different from panel ones.
- running tools OOP, where we won't be able to call JS cross processes.
- running tools in a tab, like `chrome://devtools/content/netmonitor/index.html?type=process`.

For example, it would be great if the tools were:
- relying on `unload` instead of `panel.destroy()`. But then won't have the guarantee that any of the unload handler are running to completion. (Really we should not do much during destroy!)
- starting up without a reference to a privileged/parent-process-only toolbox object. We could have an intermediate object that would help abstract launchpad/tab/toolbox as well as OOP/InParentProcess setups. Then toolbox.js and definition.js would only interact with this abstraction rather than with panel specific code.

>- decide on a consistent name for this file: "panel.js", "{toolname}-panel.js", "{toolname}.js"?

`panel.js`? It may help highlighting the connection with the code from definition.js and toolbox.js that calls panel's open/destroy. From there we call it the panel object.
https://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox.js#1666-1669
https://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox.js#1686-1688
https://searchfox.org/mozilla-central/source/devtools/client/definitions.js#10-28
But I don't have a strong opinion here. We may as well rename vars from toolbox if that helps.

>-  load this file using the BrowserLoader from definitions.js

This looks like an implementation detail, but yes, it would factorize this cryptic code.
Note that you have to instanciate one BrowserLoader per panel.

>- decide on a consistent name for the index: "index.html", "{toolname}-index.html", "{toolname}.html" (or xul, or xhtml [1])

`index.html` sounds great, like a webpage \o/

**Comment by gregtatum** [comment]
I'm not opinionated on the exact process, but I'm 💯%  behind standardizing the initialization. Whatever folks think is the best practice (as long as we document it) I'm all for it!

**Comment by jryans** [comment]
I strongly support standardizing the panel init / destroy workflow in general. It's currently a bit chaotic with each panel doing things in a slightly different way for no clear benefit.

I have a few questions about the specific proposal described here.

> The proposal is to:
> - merge "panel" and "initializer" to a single file
> - decide on a consistent name for this file: "panel.js", "{toolname}-panel.js", "{toolname}.js"?
> - load this file using the BrowserLoader from definitions.js
> - decide on a consistent name for the index: "index.html", "{toolname}-index.html", "{toolname}.html" (or xul, or xhtml [1])
> 
> Interested to know if there is some added value that I missed with having separate files here. Are there concerns or limitations linked to using the BrowserLoader for everything UI related here?

I am a bit surprised by merging the panel and initializer files, but it may also be that my thoughts are too tied down by the current status. 😅 The main distinction as I see it is that:

* panel file is loaded by the toolbox into its chrome privileged scope and serves as a "bridge" between the toolbox and the tool inside an iframe
* initializer file is loaded by the tool into its own document (could be content or chrome privileged) for tool startup

Now, it happens to be the case that every tool uses a chrome document and many use `BrowserLoader`, giving it a chrome privileged loader... Will that always be true? Do we intend to change this layer for any tools to make them more like plain web apps? 

Having two separate files keeps this responsibilities isolated from each other. Alex brought up even more scenarios that would be nice to support (OOP, in a tab, etc.) where isolation between toolbox and panel seems useful.

### Misc. Thoughts

As a side note, it may also be worth including work to [remove or standardize the panel `ready` and `destroyed` events](https://bugzilla.mozilla.org/show_bug.cgi?id=1443182).

**Comment by ochameau** [comment]
> I am a bit surprised by merging the panel and initializer files, but it may also be that my thoughts are too tied down by the current status. 😅 The main distinction as I see it is that:
> - panel file is loaded by the toolbox into its chrome privileged scope and serves as a "bridge" between the toolbox and the tool inside an iframe
> - initializer file is loaded by the tool into its own document (could be content or chrome privileged) for tool startup

I think this is confusing as we conflate the "unification of init sequence" and "how to workaround the promise issue".
To workaround the promise issue, we have to minimize all the "initializer-like" scripts to the bare minimum. It then makes them looks quite useless and easily suggest we could get rid of them completely and ensure that there is really no <script> tag anymore.
But again, outside of this promise issue, script tags are great as it looks more standard.

Overall, if I consider both aspects: unification and promises, I think it is a good idea to get rid of document scripts and only use modules until we cleanup destruction codepath and at the same time, better uncouple toolbox from panels as I described in my first comment. (no longer do direct JS calls from toolbox to panels)

**Comment by jryans** [comment]
Today, the role of panel vs. initializer is a bit fuzzy because many (all?) panel files reach inside the tool frame and poke various things inside the tool's state directly.

A better design to keep them isolated might be for the panel and initializer to communicate using `postMessage` or similar, so that there is no direct access across the frame boundary.

Anyway, that's not what we have today, so maybe it's not that relevant. After more discussion offline,  I agree it's important to solve the promise and destruction issues that prompted this RFC.

The one part that's not yet clear to me is if we _do_ combine panel and initializer as proposed, does it make it harder to support new scenarios like OOP, in tab, etc.? I assume @ochameau will have the best answer here, as I hear he is planning some demo of OOP functionality.

Overall, I am more comfortable with proceeding here given the importance of the issues this solves. It would just be nice to check if we'll end up making it a lot harder to expand functionality (towards OOP tools, tools in tab) by doing so.

**Comment by juliandescottes** [comment]
This RFC was reviewed and needs more discussion to reach a consensus about the proposal.

There is an agreement that we should unify the initialization sequence. However it is not clear if we should keep a separation between a panel file and an initializer file. The biggest concern is that merging the two files could limit our options in the future, as explained by comment from @jryans above.

Pinging @ochameau again: can we confront the proposal with the OOP plans to see if a single initialization file is a no-go?

**Comment by ochameau** [comment]
I tried looking into OOP, but making a sketch of it is already a significant work!

What I'm expecting to happen in OOP is that "Panel" class will be generic.
Panel will just be a generic class used by Toolbox to create the tool's iframe and communicate with the tool via postMessage/MessageManager/whatever-is-best to cross process boundary. The communication will mostly be about knowing when the tool is loaded and a few cross tool commands like open the given source in debugger or select given node in the inspector. Now there may be an helper on the tool side that will abstract the communication layer to not have each tool to do the postMessage/MessageManager/whatever-is-best directly. This helper may be a "Panel" class but on the other side... I don't know yet.

Given how small Panel classes are, I don't think there is any issue in merging them. It will be easy to revert/uncouple if necessary.
It may be slightly more complex to revert back to use script tags, but again, it doesn't look like a significant work. In OOP, I'm expecting tools to use a script tag for the initializer script.

I'm not concerned about doing the work back and forth. It looks straightforward, and quite limited modifications.
I'm much more concerned about the fuzz in the head of everyone, where we discourage everyone to use *any* script tag because of Promises, and then in OOP, I would like to promote them again, but only for tools that can run OOP... As getting OOP will ensure dropping any usage of possibly-zombie-Promise.

**Comment by juliandescottes** [comment]
Thanks for the feedback! From the current comments it looks like we are OK to go for a single file initialization for now, and potentially refactor when OOP becomes a reality.

**Comment by juliandescottes** [comment]
RFC was reviewed and accepted. We will turn https://bugzilla.mozilla.org/show_bug.cgi?id=1455421 into a meta bug, and log one bug per panel to migrate them. Highest priority panels to migrate are memory and performance. 

Guidelines for migration:
- merge panel.js and initializer.js to panel.js
- rename index file to index.html (or xul/xhtml when relevant)

A helper in definitions.js  should be created to build BrowserLoader instances for each panel easily.

**Comment by juliandescottes** [comment]
Haven't yet updated bugzilla/created per-panel bugs, so re-opening this.

**Comment by ochameau** [comment]
I started looking at Shader Editor as it is blocking the Promise.jsm removal.

Feedback would be much appreciated on this comment:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1470086#c3
After that, I'll try to go over all the tools that are still involving <script> tags and re-do what I did for Shader Editor.

**Comment by juliandescottes** [comment]
in progress at https://bugzilla.mozilla.org/show_bug.cgi?id=1455421
