### ISSUE TITLE
Forcing separation for let and const 

### ISSUE THREAD

**Issue by zoepage** [devtools-html/rfcs#57]
Related to #44 & https://bugzilla.mozilla.org/show_bug.cgi?id=1454696#c5

Just to make sure no one is against this, I'd like to suggest to force separation of `let` and `const` variables in deconstructing.

Now (just plate gets reassigned)
```
let apple, grapes, pear, plate;
```

Sugesstion
```
const apple, grapes, pear;
let plate;
```

Suggested change in our eslint config https://searchfox.org/mozilla-central/source/devtools/.eslintrc.js#385

Changing `"destructuring": "all"` to  `"destructuring": "any"`.

More info:
https://eslint.org/docs/rules/prefer-const

**Comment by juliandescottes** [comment]
I am in favor of this one, otherwise this can be a time waster during reviews. 

We skipped it when initially adding `prefer-const`, because it hadn't been discussed in the RFC. As said in the implementation [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1454696#c5), there were around 150 violations for this specific setting of the rule.

**Comment by captainbrosset** [comment]
Anything that avoids wasting time during code review is great! Thanks for the proposal. I'm in favor of this.

**Comment by codehag** [comment]
This looks like a good change, I am in favor of this too.

**Comment by sole** [comment]
To be explicit, this also looks like a good move to me.

**Comment by juliandescottes** [comment]
Everybody seems in favor of this, so let's accept it. @zoepage can you create a bug to implement it so that we close this?

**Comment by zoepage** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1521023
